#ifndef GPAD_VERSION_INCLUDED
#define GPAD_VERSION_INCLUDED

#define GPAD_PLUGIN_NAME "neoh4x0r-gpad-SSE"

#define GPAD_MAKE_STR_HELPER(x) #x
#define GPAD_MAKE_STR(x) GPAD_MAKE_STR_HELPER(x)

#define GPAD_VERSION_MAJOR	1
#define GPAD_VERSION_MINOR	0
#define GPAD_VERSION_PATCH	1
#define GPAD_VERSION_BETA	0
#define GPAD_VERSION_VERSTRING	GPAD_MAKE_STR(GPAD_VERSION_MAJOR) "." GPAD_MAKE_STR(GPAD_VERSION_MINOR) "." GPAD_MAKE_STR(GPAD_VERSION_PATCH) "." GPAD_MAKE_STR(GPAD_VERSION_BETA)

#define GPAD_DESCRIPTION "A plugin for the Skyrim Script Extender to improve gamepad functionality"
#define GPAD_COPYRIGHT "Copyright (C) neoh4x0r 2013-2015"

#define GPAD_PRODUCTNAME "neoh4x0r-gpad-SSE"

#endif
